### ISSUE TITLE
Undefined method `root' for EmailSerializer:Class

### ISSUE THREAD

**Issue by phr3nzii** [phstc/putsbox#13]
I'm trying to host my own version of putsbox. I believe I've got everything configured correctly however once an email has been received I am getting an error when trying to access a bucket (http://host:3000/<bucket>/inspect):
undefined method `root' for EmailSerializer:Class

The full stack is:
```
app/serializers/email_serializer.rb:2:in `<class:EmailSerializer>'
app/serializers/email_serializer.rb:1:in `<top (required)>'
activesupport (4.0.4) lib/active_support/dependencies.rb:424:in `load'
activesupport (4.0.4) lib/active_support/dependencies.rb:424:in `block in load_file'
activesupport (4.0.4) lib/active_support/dependencies.rb:616:in `new_constants_in'
activesupport (4.0.4) lib/active_support/dependencies.rb:423:in `load_file'
activesupport (4.0.4) lib/active_support/dependencies.rb:324:in `require_or_load'
activesupport (4.0.4) lib/active_support/dependencies.rb:463:in `load_missing_constant'
activesupport (4.0.4) lib/active_support/dependencies.rb:184:in `const_missing'
activesupport (4.0.4) lib/active_support/dependencies.rb:495:in `load_missing_constant'
activesupport (4.0.4) lib/active_support/dependencies.rb:184:in `const_missing'
activesupport (4.0.4) lib/active_support/dependencies.rb:495:in `load_missing_constant'
activesupport (4.0.4) lib/active_support/dependencies.rb:184:in `const_missing'
app/views/buckets/show.html.erb:33:in `block in _app_views_buckets_show_html_erb__102494096223449398_32170160'
mongoid (5.2.1) lib/mongoid/relations/referenced/many.rb:165:in `block in each'
mongoid (5.2.1) lib/mongoid/relations/targets/enumerable.rb:185:in `block in each'
mongoid (5.2.1) lib/mongoid/contextual/mongo.rb:678:in `yield_document'
mongoid (5.2.1) lib/mongoid/contextual/mongo.rb:130:in `block in each'
mongo (2.4.1) lib/mongo/collection/view/iterable.rb:45:in `block in each'
mongo (2.4.1) lib/mongo/cursor.rb:110:in `block in each'
mongo (2.4.1) lib/mongo/cursor.rb:110:in `each'
mongo (2.4.1) lib/mongo/cursor.rb:110:in `each'
mongo (2.4.1) lib/mongo/collection/view/iterable.rb:44:in `each'
mongoid (5.2.1) lib/mongoid/query_cache.rb:221:in `each'
mongoid (5.2.1) lib/mongoid/contextual/mongo.rb:129:in `each'
mongoid (5.2.1) lib/mongoid/contextual.rb:20:in `each'
mongoid (5.2.1) lib/mongoid/relations/targets/enumerable.rb:182:in `each'
mongoid (5.2.1) lib/mongoid/relations/referenced/many.rb:165:in `each'
app/views/buckets/show.html.erb:33:in `map'
app/views/buckets/show.html.erb:33:in `_app_views_buckets_show_html_erb__102494096223449398_32170160'
actionpack (4.0.4) lib/action_view/template.rb:143:in `block in render'
activesupport (4.0.4) lib/active_support/notifications.rb:161:in `instrument'
actionpack (4.0.4) lib/action_view/template.rb:141:in `render'
actionpack (4.0.4) lib/action_view/renderer/template_renderer.rb:49:in `block (2 levels) in render_template'
actionpack (4.0.4) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (4.0.4) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.0.4) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.0.4) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.0.4) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
actionpack (4.0.4) lib/action_view/renderer/template_renderer.rb:48:in `block in render_template'
actionpack (4.0.4) lib/action_view/renderer/template_renderer.rb:56:in `render_with_layout'
actionpack (4.0.4) lib/action_view/renderer/template_renderer.rb:47:in `render_template'
actionpack (4.0.4) lib/action_view/renderer/template_renderer.rb:17:in `render'
actionpack (4.0.4) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionpack (4.0.4) lib/action_view/renderer/renderer.rb:23:in `render'
actionpack (4.0.4) lib/abstract_controller/rendering.rb:127:in `_render_template'
actionpack (4.0.4) lib/action_controller/metal/streaming.rb:219:in `_render_template'
actionpack (4.0.4) lib/abstract_controller/rendering.rb:120:in `render_to_body'
actionpack (4.0.4) lib/action_controller/metal/rendering.rb:33:in `render_to_body'
actionpack (4.0.4) lib/action_controller/metal/renderers.rb:26:in `render_to_body'
actionpack (4.0.4) lib/abstract_controller/rendering.rb:97:in `render'
actionpack (4.0.4) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (4.0.4) lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
activesupport (4.0.4) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/home/ubuntu/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
activesupport (4.0.4) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (4.0.4) lib/action_controller/metal/instrumentation.rb:41:in `block in render'
actionpack (4.0.4) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
actionpack (4.0.4) lib/action_controller/metal/instrumentation.rb:40:in `render'
actionpack (4.0.4) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
actionpack (4.0.4) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
actionpack (4.0.4) lib/abstract_controller/base.rb:189:in `process_action'
actionpack (4.0.4) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.0.4) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (4.0.4) lib/active_support/callbacks.rb:414:in `block in _run__1256984734204533682__process_action__callbacks'
activesupport (4.0.4) lib/active_support/callbacks.rb:212:in `block in _conditional_callback_around_19'
/home/ubuntu/.rvm/gems/ruby-2.3.3/bundler/gems/react-rails-6642ae0c4495/lib/react/rails/controller_lifecycle.rb:31:in `use_react_component_helper'
activesupport (4.0.4) lib/active_support/callbacks.rb:211:in `_conditional_callback_around_19'
activesupport (4.0.4) lib/active_support/callbacks.rb:383:in `_run__1256984734204533682__process_action__callbacks'
activesupport (4.0.4) lib/active_support/callbacks.rb:80:in `run_callbacks'
actionpack (4.0.4) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (4.0.4) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.0.4) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (4.0.4) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.0.4) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.0.4) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.0.4) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.0.4) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
actionpack (4.0.4) lib/abstract_controller/base.rb:136:in `process'
actionpack (4.0.4) lib/abstract_controller/rendering.rb:44:in `process'
actionpack (4.0.4) lib/action_controller/metal.rb:195:in `dispatch'
actionpack (4.0.4) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.0.4) lib/action_controller/metal.rb:231:in `block in action'
actionpack (4.0.4) lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
actionpack (4.0.4) lib/action_dispatch/routing/route_set.rb:48:in `call'
actionpack (4.0.4) lib/action_dispatch/journey/router.rb:71:in `block in call'
actionpack (4.0.4) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.0.4) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.0.4) lib/action_dispatch/routing/route_set.rb:674:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (1.5.5) lib/rack/etag.rb:23:in `call'
rack (1.5.5) lib/rack/conditionalget.rb:25:in `call'
rack (1.5.5) lib/rack/head.rb:11:in `call'
actionpack (4.0.4) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.0.4) lib/action_dispatch/middleware/flash.rb:241:in `call'
rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.0.4) lib/action_dispatch/middleware/cookies.rb:486:in `call'
actionpack (4.0.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.0.4) lib/active_support/callbacks.rb:373:in `_run__3219953942721367397__call__callbacks'
activesupport (4.0.4) lib/active_support/callbacks.rb:80:in `run_callbacks'
actionpack (4.0.4) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.0.4) lib/action_dispatch/middleware/reloader.rb:64:in `call'
actionpack (4.0.4) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
actionpack (4.0.4) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.0.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.0.4) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.0.4) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.0.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.0.4) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.0.4) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.0.4) lib/rails/rack/logger.rb:20:in `call'
quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
actionpack (4.0.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
rack (1.5.5) lib/rack/runtime.rb:17:in `call'
activesupport (4.0.4) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
rack (1.5.5) lib/rack/lock.rb:17:in `call'
actionpack (4.0.4) lib/action_dispatch/middleware/static.rb:64:in `call'
rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
railties (4.0.4) lib/rails/engine.rb:511:in `call'
railties (4.0.4) lib/rails/application.rb:97:in `call'
rack (1.5.5) lib/rack/lock.rb:17:in `call'
rack (1.5.5) lib/rack/content_length.rb:14:in `call'
rack (1.5.5) lib/rack/handler/webrick.rb:60:in `service'
/home/ubuntu/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/home/ubuntu/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/home/ubuntu/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

Any idea how this can be fixed?

**Comment by phstc** [comment]
@phr3nzii hm the inspect URL `http://host:3000//inspect` is missing the bucket name, it should be `http://host:3000/something-bucket-name/inspect`, could you try that?

**Comment by phr3nzii** [comment]
Sorry, that is a typo. I meant to put http://host:3000/<bucket>/inspect

This is happening for all buckets

**Comment by phstc** [comment]
@phr3nzii hehe you need to backtick `<bucket>`, otherwise GH will consider it as markup and won't show it.

Getting back to the issue - did you `bundle install`? Try to inspect this https://github.com/phstc/putsbox/blob/master/app/views/buckets/show.html.erb#L33, check how `@bucket.emails` is populated.

**Comment by phr3nzii** [comment]
Oh I see, oops!

Yeah I ran `bundle install`. I'll take a look and see how far I get

**Comment by phstc** [comment]
@phr3nzii you may try `binding.pry` [here](https://github.com/phstc/putsbox/blob/master/app/controllers/buckets_controller.rb#L27) to inspect that. 

Did you configure a SendGrid account for receiving emails?

Pls let me know how it looks.

**Comment by phr3nzii** [comment]
I'm going to close this issue as I am no longer pursuing hosting our own PutsBox
